swagger: '2.0'
info:
  version: 1.0.0
  title: Smart Serve
  description: Smart Serve API Documents
  contact:
    name: Smart Serve
    url: 'https://github.com/WasimAkramRana/smartServe.git'
host: '104.211.74.123:3090'
basePath: /
schemes:
  - http
  - https
securityDefinitions:
  JWT:
    type: apiKey
    name: x-access-token
    in: header
    description: Enter valid API authorization token
tags:
  - name: User Controller
    description: API to manage users.
  - name: Restaurant Controller
    description: API to manage Restaurant
  - name: Product Controller
    description: API to manage Products of Restaurant
  - name: Server Endpoint
    description: Check server running status
paths:
  /user/signup:
    post:
      tags:
        - User Controller
      summary: This api is used add new user
      operationId: userSignup
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: firstName
          in: formData
          type: string
          required: true
        - name: lastName
          in: formData
          type: string
          required: true
        - name: phone
          in: formData
          type: string
          required: true
        - name: password
          in: formData
          type: string
          required: true
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/SuccessResponse'
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /user/login:
    post:
      tags:
        - User Controller
      summary: This api is used login and get JWT token
      operationId: userLogin
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: phone
          in: formData
          type: string
          required: true
        - name: password
          in: formData
          type: string
          required: true
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/SuccessResponse'
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /restaurant/exists:
    get:
      tags: 
        - Restaurant Controller
      summary: This API is used to verify that restaurant name already exists or not
      operationId: restaurantExists
      produces:
        - application/json
      parameters: 
        - name: name
          in: query
          type: string
          required: true
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/SuccessResponse'
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /restaurant:
    get:
      tags:
        - Restaurant Controller
      summary: This API return list of restaurants
      operationId: getRestaurant
      produces:
        - application/json
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/SuccessResponse'
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
    post:
      tags:
        - Restaurant Controller
      summary: This API is used to add new restaurant
      operationId: addRestaurant
      produces:
        - application/json
      parameters:
        - name: Restaurant
          in: body
          schema:
            $ref: '#/definitions/Restaurant'
          required: true
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/SuccessResponse'
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  '/restaurant/{restaurantId}':
    put:
      tags:
        - Restaurant Controller
      summary: This API is used update exits restaurant
      operationId: updateRestaurant
      produces:
        - application/json
      parameters:
        - name: restaurantId
          in: path
          type: string
          required: true
        - name: Restaurant
          in: body
          schema:
            $ref: '#/definitions/Restaurant'
          required: true
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/SuccessResponse'
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
    delete:
      tags:
        - Restaurant Controller
      summary: This API delete particular restaurant
      operationId: deleteRestaurant
      produces:
        - application/json
      parameters:
        - name: restaurantId
          in: path
          type: string
          required: true
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/SuccessResponse'
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /:
    get:
      tags:
        - Server Endpoint
      summary: This api is used to check server is running or not
      operationId: serverRunning
      produces:
        - text/plain
      responses:
        default:
          description: Return server running status.
  /product/{restaurantId}/exists:
    get:
      tags: 
        - Product Controller
      summary: This API is used to verify that product name already exists or not
      operationId: productExists
      produces:
        - application/json
      parameters: 
        - name: restaurantId
          in: path
          type: string
          required: true
        - name: name
          in: query
          type: string
          required: true
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/SuccessResponse'
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  '/product/{restaurantId}':
    get:
      tags:
        - Product Controller
      summary: This API get products of particular restaurant with search options
      description: >-
        isVeg (true / false) and name (Product Name) is optional parameter to
        search products
      operationId: getProducts
      produces:
        - application/json
      parameters:
        - name: restaurantId
          in: path
          type: string
          required: true
        - name: isVeg
          in: query
          type: boolean
        - name: name
          in: query
          type: string
        - name: isAvaliable
          in: query
          type: boolean
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/SuccessResponse'
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
    post:
      tags:
        - Product Controller
      summary: This API is used to add new product in particular restaurant
      operationId: addProduct
      produces:
        - application/json
      parameters:
        - name: restaurantId
          in: path
          type: string
          required: true
        - name: products
          in: body
          required: true
          schema:
            $ref: '#/definitions/Products'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/SuccessResponse'
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  '/product/{restaurantId}/{productId}':
    put:
      tags:
        - Product Controller
      summary: This API is used to update product in particular restaurant
      operationId: updateProduct
      produces:
        - application/json
      parameters:
        - name: restaurantId
          in: path
          type: string
          required: true
        - name: productId
          in: path
          type: string
          required: true
        - name: products
          in: body
          required: true
          schema:
            $ref: '#/definitions/Products'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/SuccessResponse'
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
    delete:
      tags:
        - Product Controller
      summary: This API delete particular product of particular restaurant
      operationId: deleteProducts
      produces:
        - application/json
      parameters:
        - name: restaurantId
          in: path
          type: string
          required: true
        - name: productId
          in: path
          type: string
          required: true
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/SuccessResponse'
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
definitions:
  SuccessResponse:
    type: object
    properties:
      status:
        type: string
        example: success
      message:
        type: string
        example: Successfully job done.
      data:
        type: object
        description: Required result object or array of data.
  ErrorResponse:
    type: object
    properties:
      status:
        type: string
        example: error
      message:
        type: string
        description: Error message.
        example: Network error found. Please try after some time.
  Restaurant:
    type: object
    properties:
      name:
        type: string
      serviceTaxNo:
        type: string
      CSTNo:
        type: string
      SGSTNo:
        type: string
      location:
        type: string
      contactPerson:
        type: string
      mobile:
        type: string
      tables:
        type: array
        items:
          type: string
  Products:
    type: object
    properties:
      name:
        type: string
      imageUrl:
        type: string
      isVeg:
        type: boolean
      details:
        type: string
      isAvaliable:
        type: boolean
      unit:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            price:
              type: number
            offerPrice:
              type: number
